language: node_js
node_js:
  - "10"
install:
  - npm install
script:
  - npm run build
cache:
  directories:
    - "node_modules"    
deploy:
  local_dir: dist/
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  on:
    branch: master
